[package]
name = "engine-scene"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
